# Generated by Django 5.1.1 on 2024-09-28 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='accent_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit hex color code', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AlterField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(default='#808080', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit hex color code', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
    ]
