# Generated by Django 5.1.1 on 2024-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
    ]
