# Generated by Django 5.1.1 on 2024-09-28 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_accent_color_alter_store_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(default='#e8e8e8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit hex color code', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
    ]
