# Generated by Django 5.1.1 on 2024-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tag_line',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
