# Generated by Django 5.1.1 on 2024-09-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_accent_color_store_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='secondary_color',
        ),
    ]
