# Generated by Django 5.1.1 on 2024-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='secondary_color',
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
