# Generated by Django 5.1.1 on 2024-09-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, help_text="Enter the icon name (e.g., 'facebook', 'twitter')", max_length=50, null=True),
        ),
    ]
