# Generated by Django 5.1.1 on 2024-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_options_sociallink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, upload_to='logos/'),
        ),
    ]
